global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-email-notifications'

receivers:
- name: 'slack-email-notifications'
  slack_configs:
  - channel: '#mikhail_androsov'
  email_configs:
    - to: $GMAIL_ACCOUNT
      from: $GMAIL_ACCOUNT
      smarthost: smtp.gmail.com:587
      auth_username: $GMAIL_ACCOUNT
      auth_identity: $GMAIL_ACCOUNT
      auth_password: $GMAIL_PASSWORD
