version: "3.3"
services:
  blackbox-exporter:
    image: ${USERNAME}/blackbox-exporter:1.0
    container_name: blackbox-exporter
    ports:
      - '9115:9115'
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - back_net

  mongodb-exporter:
    image: ${USERNAME}/mongodb-exporter:1.0
    container_name: mongodb-exporter
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    container_name: node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  prometheus:
    image: ${USERNAME}/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  grafana:
    image: ${USER_NAME}/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - back_net

  cadvisor:
    image: google/cadvisor:v0.29.0
    container_name: cadvisor
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - back_net

  telegraf:
    image: ${USER_NAME}/telegraf
    container_name: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - back_net

  stackdriver:
    image: ${USER_NAME}/stackdriver
    container_name: stackdriver
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/key/project.json
      - STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID=VERY_SECRET_PROJECT
      - STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES=compute.googleapis.com/instance,pubsub.googleapis.com/subscription,redis.googleapis.com/stats
    ports:
      - '9255:9255'
    networks:
      - back_net

  alertmanager:
    image: ${USER_NAME}/alertmanager
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - back_net

networks:
  front_net:
  back_net:

volumes:
  prometheus_data:
  grafana_data:
