datasources:
    -  access: 'proxy'
       editable: true
       is_default: true
       name: 'Prometheus server'
       org_id: 1
       type: 'prometheus'
       url: 'http://prometheus:9090'
       version: 1

    - name: prom-trickster-memory-stdout
      type: prometheus
      access: proxy
      orgId: 1
      uid: ds_prom1_trickster
      url: http://trickster:8480/prom1
      version: 1
      editable: true
