version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: mongo_db
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    container_name: ui
    ports:
      - ${PORT}:${PORT}
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    container_name: post
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    container_name: comment
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
